# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('baseurl', models.CharField(max_length=128)),
                ('baseurl_ftp', models.CharField(max_length=128)),
                ('baseurl_rsync', models.CharField(max_length=128)),
                ('enabled', models.BooleanField()),
                ('status_baseurl', models.BooleanField()),
                ('region', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=2)),
                ('asn', models.IntegerField()),
                ('prefix', models.CharField(max_length=18)),
                ('score', models.SmallIntegerField()),
                ('scan_fpm', models.IntegerField()),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField()),
                ('operator_name', models.CharField(max_length=128)),
                ('operator_url', models.CharField(max_length=128)),
                ('public_notes', models.CharField(max_length=512)),
                ('admin', models.CharField(max_length=128)),
                ('admin_email', models.CharField(max_length=128)),
                ('lat', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('country_only', models.BooleanField()),
                ('region_only', models.BooleanField()),
                ('as_only', models.BooleanField()),
                ('prefix_only', models.BooleanField()),
                ('other_countries', models.CharField(max_length=512)),
                ('file_maxsize', models.IntegerField()),
                ('ipv6_only', models.BooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'server',
            },
        ),
    ]
